Etu\Core\ApiBundle\Entity\Scope:
    type: entity
    table: oauth_scope
    id:
        scope:
            type:       string
            length:     255
    fields:
        description:
            type:       string
            length:     255
    lifecycleCallbacks: {  }