
# Load the core routes
etu_core:
    resource: "@EtuCoreBundle/Controller/"
    type:     annotation
    prefix:   /


# Load the user routes
etu_user:
    resource: "@EtuUserBundle/Controller/"
    type:     annotation
    prefix:   /


# Load FOS Routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


# Load modules routes
etu_modules:
    resource: .
    type:     modules
    prefix:   /


# API doc
etu_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc/reference

etu_api_panel:
    resource: "@EtuCoreApiBundle/Controller/"
    type:     annotation
    prefix:   /api

# Load API from modules
etu_api:
    resource: .
    type:     api
    prefix:   /api

artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:     annotation
    prefix:   /filemanager